import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { cn } from '@/utils';
import { LoaderCircle, X } from 'lucide-react';

export const Button = ({ className, variant = 'secondary', size = 'md', loading, children, as: _as, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary'|'secondary'|'ghost'|'danger'; size?: 'sm'|'md'|'icon'; loading?: boolean; as?: string }) => { const Tag = _as === 'span' ? 'span' : 'button'; return <Tag className={cn('focus-ring inline-flex items-center justify-center gap-2 rounded-lg font-medium transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50', variant === 'primary' && 'bg-accent text-white shadow-glow hover:bg-[#8c7fff]', variant === 'secondary' && 'border border-line bg-panel text-slate-100 hover:bg-[#191c25]', variant === 'ghost' && 'text-muted hover:bg-[#1c1f28] hover:text-white', variant === 'danger' && 'border border-red-500/30 bg-red-500/10 text-red-300 hover:bg-red-500/20', size === 'sm' && 'h-8 px-3 text-xs', size === 'md' && 'h-10 px-4 text-sm', size === 'icon' && 'h-9 w-9', className)} {...props}>{loading && <LoaderCircle size={15} className="animate-spin" />}{children}</Tag>; };
export const Card = ({ className, children }: { className?: string; children: ReactNode }) => <section className={cn('glass rounded-2xl', className)}>{children}</section>;
export const Badge = ({ tone = 'neutral', children }: { tone?: 'neutral'|'purple'|'green'|'yellow'|'red'|'blue'; children: ReactNode }) => <span className={cn('inline-flex items-center rounded-md border px-2 py-0.5 text-[11px] font-medium', tone === 'neutral' && 'border-line bg-[#191c23] text-muted', tone === 'purple' && 'border-accent/30 bg-accent/10 text-violet-200', tone === 'green' && 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300', tone === 'yellow' && 'border-amber-500/30 bg-amber-500/10 text-amber-300', tone === 'red' && 'border-red-500/30 bg-red-500/10 text-red-300', tone === 'blue' && 'border-sky-500/30 bg-sky-500/10 text-sky-300')}>{children}</span>;
export const Input = ({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) => <input className={cn('focus-ring h-10 w-full rounded-lg border border-line bg-[#0e1015] px-3 text-sm text-white placeholder:text-muted/60', className)} {...props} />;
export const Textarea = ({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) => <textarea className={cn('focus-ring min-h-24 w-full resize-y rounded-lg border border-line bg-[#0e1015] px-3 py-2 text-sm text-white placeholder:text-muted/60', className)} {...props} />;
export const EmptyState = ({ icon, title, description, action }: { icon: ReactNode; title: string; description: string; action?: ReactNode }) => <div className="flex flex-col items-center justify-center py-20 text-center"><div className="mb-4 rounded-2xl border border-line bg-panel p-4 text-muted">{icon}</div><h3 className="text-base font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted">{description}</p>{action && <div className="mt-5">{action}</div>}</div>;
export const Progress = ({ value, tone = 'purple' }: { value: number; tone?: 'purple'|'green'|'yellow' }) => <div className="h-1.5 overflow-hidden rounded-full bg-[#262a35]"><div className={cn('h-full rounded-full transition-all', tone === 'purple' && 'bg-accent', tone === 'green' && 'bg-emerald-400', tone === 'yellow' && 'bg-amber-400')} style={{ width: `${Math.max(0, Math.min(value, 100))}%` }} /></div>;
export const Modal = ({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-6 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="glass max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><Button variant="ghost" size="icon" aria-label="Close" onClick={onClose}><X size={18}/></Button></div>{children}</div></div>;
export const SectionTitle = ({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) => <div className="mb-6 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-muted">{description}</p>}</div>{actions && <div className="flex items-center gap-2">{actions}</div>}</div>;
